### ISSUE TITLE
数据库错误

### ISSUE THREAD

**Issue by learder** [Zzzia/Book#4]
机型：小米MIX2S
ROM版本：MIUI 10 9.6.20 | 开发版
 android版本：9
如何发生：打开app，进入首页
是否复现：否

====================================

android.database.sqlite.SQLiteException: index index_bookCache_siteName_bookName_index already exists (code 1 SQLITE_ERROR): , while compiling: CREATE UNIQUE INDEX `index_bookCache_siteName_bookName_index` ON `bookCache` (`siteName`, `bookName`, `index`)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1770)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
	at a.f.a.a.b.b(FrameworkSQLiteDatabase.java:242)
	at com.zia.database.AppDatabase_Impl$1.createAllTables(AppDatabase_Impl.java:52)
	at androidx.room.u.c(RoomOpenHelper.java:74)
	at a.f.a.a.d$a.onCreate(FrameworkSQLiteOpenHelper.java:118)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at a.f.a.a.d$a.m(FrameworkSQLiteOpenHelper.java:92)
	at a.f.a.a.d.a(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
	at com.zia.database.bean.LocalBookDao_Impl.getLocalBooks(LocalBookDao_Impl.java:196)
	at com.zia.page.bookrack.t.run(BookRackModel.kt:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.zia.util.threadPool.c.run(PriorityThreadFactory.java:23)
	at java.lang.Thread.run(Thread.java:764)

**Comment by Zzzia** [comment]
感谢反馈，这个问题已知，但不敢修改数据库结构，怕引起兼容问题..
